apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: novatrack
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "novatrack-api"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["novatrack-api:80"]
