apiVersion: v1
kind: Service
metadata:
  name: novatrack-api
  namespace: novatrack
spec:
  type: NodePort
  selector:
    app: novatrack-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080